version: '3.4'
services:
  webapi:
    image: bankingapi
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: '/app'
    ports:
      - "5001:80"
    environment: 
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=http://+:80
    entrypoint:
      ["dotnet", "BankingApi.dll"]
